
worksheets: W*.ipynb
	cp *.tplx _build/
	cp W*ipynb _build/
	make -C _build Worksheet1_Notebook.pdf
	make -C _build Worksheet2_Notebook.pdf
	make -C _build Worksheet3_Notebook.pdf
	make -C _build Worksheet4_Notebook.pdf
	make -C _build Worksheet5_Notebook.pdf
	make -C _build Worksheet6_Notebook.pdf
	make -C _build Worksheet7_Notebook.pdf
	make -C _build clean
